export const dataKeyRu = [
  {
    id: 'key-01',
    code: 'Backquote',
    value: 'ё',
    type: 'alphanumeric',
  },
  {
    id: 'key-02',
    code: 'Digit1',
    value: '1',
    type: 'alphanumeric',
  },
  {
    id: 'key-03',
    code: 'Digit2',
    value: '2',
    type: 'alphanumeric',
  },
  {
    id: 'key-04',
    code: 'Digit3',
    value: '3',
    type: 'alphanumeric',
  },
  {
    id: 'key-05',
    code: 'Digit4',
    value: '4',
    type: 'alphanumeric',
  },
  {
    id: 'key-06',
    code: 'Digit5',
    value: '5',
    type: 'alphanumeric',
  },
  {
    id: 'key-07',
    code: 'Digit6',
    value: '6',
    type: 'alphanumeric',
  },
  {
    id: 'key-08',
    code: 'Digit7',
    value: '7',
    type: 'alphanumeric',
  },
  {
    id: 'key-09',
    code: 'Digit8',
    value: '8',
    type: 'alphanumeric',
  },
  {
    id: 'key-10',
    code: 'Digit9',
    value: '9',
    type: 'alphanumeric',
  },
  {
    id: 'key-11',
    code: 'Digit0',
    value: '0',
    type: 'alphanumeric',
  },
  {
    id: 'key-12',
    code: 'Minus',
    value: '-',
    type: 'alphanumeric',
  },
  {
    id: 'key-13',
    code: 'Equal',
    value: '=',
    type: 'alphanumeric',
  },
  {
    id: 'key-14',
    code: 'Backspace',
    value: 'Backspace',
    type: 'functional',
  },
  {
    id: 'key-15',
    code: 'Tab',
    value: 'Tab',
    type: 'functional',
  },
  {
    id: 'key-16',
    code: 'KeyQ',
    value: 'й',
    type: 'alphanumeric',
  },
  {
    id: 'key-17',
    code: 'KeyW',
    value: 'ц',
    type: 'alphanumeric',
  },
  {
    id: 'key-18',
    code: 'KeyE',
    value: 'у',
    type: 'alphanumeric',
  },
  {
    id: 'key-19',
    code: 'KeyR',
    value: 'к',
    type: 'alphanumeric',
  },
  {
    id: 'key-20',
    code: 'KeyT',
    value: 'е',
    type: 'alphanumeric',
  },
  {
    id: 'key-21',
    code: 'Key-Y',
    value: 'н',
    type: 'alphanumeric',
  },
  {
    id: 'key-22',
    code: 'KeyU',
    value: 'г',
    type: 'alphanumeric',
  },
  {
    id: 'key-23',
    code: 'KeyI',
    value: 'ш',
    type: 'alphanumeric',
  },
  {
    id: 'key-24',
    code: 'KeyO',
    value: 'щ',
    type: 'alphanumeric',
  },
  {
    id: 'key-25',
    code: 'KeyP',
    value: 'з',
    type: 'alphanumeric',
  },
  {
    id: 'key-26',
    code: 'BracketLeft',
    value: 'х',
    type: 'alphanumeric',
  },
  {
    id: 'key-27',
    code: 'BracketRight',
    value: 'ъ',
    type: 'alphanumeric',
  },
  {
    id: 'key-28',
    code: 'Backslash',
    value: '\\',
    type: 'alphanumeric',
  },
  {
    id: 'key-29',
    code: 'Delete',
    value: 'Del',
    type: 'control',
  },
  {
    id: 'key-30',
    code: 'CapsLock',
    value: 'Caps Lock',
    type: 'functional',
  },
  {
    id: 'key-31',
    code: 'KeyA',
    value: 'ф',
    type: 'alphanumeric',
  },
  {
    id: 'key-32',
    code: 'KeyS',
    value: 'ы',
    type: 'alphanumeric',
  },
  {
    id: 'key-33',
    code: 'KeyD',
    value: 'в',
    type: 'alphanumeric',
  },
  {
    id: 'key-34',
    code: 'KeyF',
    value: 'а',
    type: 'alphanumeric',
  },
  {
    id: 'key-35',
    code: 'KeyG',
    value: 'п',
    type: 'alphanumeric',
  },
  {
    id: 'key-36',
    code: 'KeyH',
    value: 'р',
    type: 'alphanumeric',
  },
  {
    id: 'key-37',
    code: 'KeyJ',
    value: 'о',
    type: 'alphanumeric',
  },
  {
    id: 'key-38',
    code: 'KeyK',
    value: 'л',
    type: 'alphanumeric',
  },
  {
    id: 'key-39',
    code: 'KeyL',
    value: 'д',
    type: 'alphanumeric',
  },
  {
    id: 'key-40',
    code: 'Semicolon',
    value: 'ж',
    type: 'alphanumeric',
  },
  {
    id: 'key-41',
    code: 'Quote',
    value: 'э',
    type: 'alphanumeric',
  },
  {
    id: 'key-42',
    code: 'Enter',
    value: 'Enter',
    type: 'functional',
  },
  {
    id: 'key-43',
    code: 'ShiftLeft',
    value: 'Shift',
    type: 'functional',
  },
  {
    id: 'key-44',
    code: 'KeyZ',
    value: 'я',
    type: 'alphanumeric',
  },
  {
    id: 'key-45',
    code: 'KeyX',
    value: 'ч',
    type: 'alphanumeric',
  },
  {
    id: 'key-46',
    code: 'KeyC',
    value: 'с',
    type: 'alphanumeric',
  },
  {
    id: 'key-47',
    code: 'KeyV',
    value: 'м',
    type: 'alphanumeric',
  },
  {
    id: 'key-48',
    code: 'KeyB',
    value: 'и',
    type: 'alphanumeric',
  },
  {
    id: 'key-49',
    code: 'KeyN',
    value: 'т',
    type: 'alphanumeric',
  },
  {
    id: 'key-50',
    code: 'KeyM',
    value: 'ь',
    type: 'alphanumeric',
  },
  {
    id: 'key-51',
    code: 'Comma',
    value: 'б',
    type: 'alphanumeric',
  },
  {
    id: 'key-52',
    code: 'Period',
    value: 'ю',
    type: 'alphanumeric',
  },
  {
    id: 'key-53',
    code: 'Slash',
    value: '.',
    type: 'alphanumeric',
  },
  {
    id: 'key-54',
    code: 'ArrowUp',
    value: '↑',
    type: 'arrow',
  },
  {
    id: 'key-55',
    code: 'ShiftRight',
    value: 'Shift',
    type: 'functional',
  },
  {
    id: 'key-56',
    code: 'ControlLeft',
    value: 'Ctrl',
    type: 'functional',
  },
  {
    id: 'key-57',
    code: 'MetaLeft',
    value: 'Win',
    type: 'functional',
  },
  {
    id: 'key-58',
    code: 'AltLeft',
    value: 'Alt',
    type: 'functional',
  },
  {
    id: 'key-59',
    code: 'Space',
    value: 'Space',
    type: 'functional',
  },
  {
    id: 'key-60',
    code: 'AltRight',
    value: 'Alt',
    type: 'functional',
  },
  {
    id: 'key-61',
    code: 'ArrowLeft',
    value: '←',
    type: 'arrow',
  },
  {
    id: 'key-62',
    code: 'ArrowDown',
    value: '↓',
    type: 'arrow',
  },
  {
    id: 'key-63',
    code: 'ArrowRight',
    value: '→',
    type: 'arrow',
  },
  {
    id: 'key-64',
    code: 'ControlRight',
    value: 'Ctrl',
    type: 'functional',
  },
];
export const dataKeyEn = [
  {
    id: 'key-01',
    code: 'Backquote',
    value: '`',
    type: 'alphanumeric',
  },
  {
    id: 'key-02',
    code: 'Digit1',
    value: '1',
    type: 'alphanumeric',
  },
  {
    id: 'key-03',
    code: 'Digit2',
    value: '2',
    type: 'alphanumeric',
  },
  {
    id: 'key-04',
    code: 'Digit3',
    value: '3',
    type: 'alphanumeric',
  },
  {
    id: 'key-05',
    code: 'Digit4',
    value: '4',
    type: 'alphanumeric',
  },
  {
    id: 'key-06',
    code: 'Digit5',
    value: '5',
    type: 'alphanumeric',
  },
  {
    id: 'key-07',
    code: 'Digit6',
    value: '6',
    type: 'alphanumeric',
  },
  {
    id: 'key-08',
    code: 'Digit7',
    value: '7',
    type: 'alphanumeric',
  },
  {
    id: 'key-09',
    code: 'Digit8',
    value: '8',
    type: 'alphanumeric',
  },
  {
    id: 'key-10',
    code: 'Digit9',
    value: '9',
    type: 'alphanumeric',
  },
  {
    id: 'key-11',
    code: 'Digit0',
    value: '0',
    type: 'alphanumeric',
  },
  {
    id: 'key-12',
    code: 'Minus',
    value: '-',
    type: 'alphanumeric',
  },
  {
    id: 'key-13',
    code: 'Equal',
    value: '=',
    type: 'alphanumeric',
  },
  {
    id: 'key-14',
    code: 'Backspace',
    value: 'Backspace',
    type: 'functional',
  },
  {
    id: 'key-15',
    code: 'Tab',
    value: 'Tab',
    type: 'functional',
  },
  {
    id: 'key-16',
    code: 'KeyQ',
    value: 'q',
    type: 'alphanumeric',
  },
  {
    id: 'key-17',
    code: 'KeyW',
    value: 'w',
    type: 'alphanumeric',
  },
  {
    id: 'key-18',
    code: 'KeyE',
    value: 'e',
    type: 'alphanumeric',
  },
  {
    id: 'key-19',
    code: 'KeyR',
    value: 'r',
    type: 'alphanumeric',
  },
  {
    id: 'key-20',
    code: 'KeyT',
    value: 't',
    type: 'alphanumeric',
  },
  {
    id: 'key-21',
    code: 'KeyY',
    value: 'y',
    type: 'alphanumeric',
  },
  {
    id: 'key-22',
    code: 'KeyU',
    value: 'u',
    type: 'alphanumeric',
  },
  {
    id: 'key-23',
    code: 'KeyI',
    value: 'i',
    type: 'alphanumeric',
  },
  {
    id: 'key-24',
    code: 'KeyO',
    value: 'o',
    type: 'alphanumeric',
  },
  {
    id: 'key-25',
    code: 'KeyP',
    value: 'p',
    type: 'alphanumeric',
  },
  {
    id: 'key-26',
    code: 'BracketLeft',
    value: '[',
    type: 'alphanumeric',
  },
  {
    id: 'key-27',
    code: 'BracketRight',
    value: ']',
    type: 'alphanumeric',
  },
  {
    id: 'key-28',
    code: 'Backslash',
    value: '\\',
    type: 'alphanumeric',
  },
  {
    id: 'key-29',
    code: 'Delete',
    value: 'Del',
    type: 'control',
  },
  {
    id: 'key-30',
    code: 'CapsLock',
    value: 'Caps Lock',
    type: 'functional',
  },
  {
    id: 'key-31',
    code: 'KeyA',
    value: 'a',
    type: 'alphanumeric',
  },
  {
    id: 'key-32',
    code: 'KeyS',
    value: 's',
    type: 'alphanumeric',
  },
  {
    id: 'key-33',
    code: 'KeyD',
    value: 'd',
    type: 'alphanumeric',
  },
  {
    id: 'key-34',
    code: 'KeyF',
    value: 'f',
    type: 'alphanumeric',
  },
  {
    id: 'key-35',
    code: 'KeyG',
    value: 'g',
    type: 'alphanumeric',
  },
  {
    id: 'key-36',
    code: 'KeyH',
    value: 'h',
    type: 'alphanumeric',
  },
  {
    id: 'key-37',
    code: 'KeyJ',
    value: 'j',
    type: 'alphanumeric',
  },
  {
    id: 'key-38',
    code: 'KeyK',
    value: 'k',
    type: 'alphanumeric',
  },
  {
    id: 'key-39',
    code: 'KeyL',
    value: 'l',
    type: 'alphanumeric',
  },
  {
    id: 'key-40',
    code: 'Semicolon',
    value: ';',
    type: 'alphanumeric',
  },
  {
    id: 'key-41',
    code: 'Quote',
    value: '\'',
    type: 'alphanumeric',
  },
  {
    id: 'key-42',
    code: 'Enter',
    value: 'Enter',
    type: 'functional',
  },
  {
    id: 'key-43',
    code: 'ShiftLeft',
    value: 'Shift',
    type: 'functional',
  },
  {
    id: 'key-44',
    code: 'KeyZ',
    value: 'z',
    type: 'alphanumeric',
  },
  {
    id: 'key-45',
    code: 'KeyX',
    value: 'x',
    type: 'alphanumeric',
  },
  {
    id: 'key-46',
    code: 'KeyC',
    value: 'c',
    type: 'alphanumeric',
  },
  {
    id: 'key-47',
    code: 'KeyV',
    value: 'v',
    type: 'alphanumeric',
  },
  {
    id: 'key-48',
    code: 'KeyB',
    value: 'b',
    type: 'alphanumeric',
  },
  {
    id: 'key-49',
    code: 'KeyN',
    value: 'n',
    type: 'alphanumeric',
  },
  {
    id: 'key-50',
    code: 'KeyM',
    value: 'm',
    type: 'alphanumeric',
  },
  {
    id: 'key-51',
    code: 'Comma',
    value: ',',
    type: 'alphanumeric',
  },
  {
    id: 'key-52',
    code: 'Period',
    value: '.',
    type: 'alphanumeric',
  },
  {
    id: 'key-53',
    code: 'Slash',
    value: '/',
    type: 'alphanumeric',
  },
  {
    id: 'key-54',
    code: 'ArrowUp',
    value: '↑',
    type: 'arrow',
  },
  {
    id: 'key-55',
    code: 'ShiftRight',
    value: 'Shift',
    type: 'functional',
  },
  {
    id: 'key-56',
    code: 'ControlLeft',
    value: 'Ctrl',
    type: 'functional',
  },
  {
    id: 'key-57',
    code: 'MetaLeft',
    value: 'Win',
    type: 'functional',
  },
  {
    id: 'key-58',
    code: 'AltLeft',
    value: 'Alt',
    type: 'functional',
  },
  {
    id: 'key-59',
    code: 'Space',
    value: 'Space',
    type: 'functional',
  },
  {
    id: 'key-60',
    code: 'AltRight',
    value: 'Alt',
    type: 'functional',
  },
  {
    id: 'key-61',
    code: 'ArrowLeft',
    value: '←',
    type: 'arrow',
  },
  {
    id: 'key-62',
    code: 'ArrowDown',
    value: '↓',
    type: 'arrow',
  },
  {
    id: 'key-63',
    code: 'ArrowRight',
    value: '→',
    type: 'arrow',
  },
  {
    id: 'key-64',
    code: 'ControlRight',
    value: 'Ctrl',
    type: 'functional',
  },
];
export const keyEnShift = [
  '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', 'Backspace',
  'Tab', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '|', 'Del',
  'Caps Lock', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', 'Enter',
  'Shift', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?', '↑', 'Shift',
  'Ctrl', 'Win', 'Alt', 'Space', 'Alt', '←', '↓', '→', 'Ctrl',
];
export const keyEnShiftSmall = [
  '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', 'Backspace',
  'Tab', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '{', '}', '|', 'Del',
  'Caps Lock', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ':', '"', 'Enter',
  'Shift', 'z', 'x', 'c', 'v', 'b', 'n', 'm', '<', '>', '?', '↑', 'Shift',
  'Ctrl', 'Win', 'Alt', 'Space', 'Alt', '←', '↓', '→', 'Ctrl',
];
export const keyRuShift = [
  'Ё', '!', '"', '№', ';', '%', ':', '?', '*', '(', ')', '_', '+', 'Backspace',
  'Tab', 'Й', 'Ц', 'У', 'К', 'Е', 'Н', 'Г', 'Ш', 'Щ', 'З', 'Х', 'Ъ', '|', 'Del',
  'Caps Lock', 'Ф', 'Ы', 'В', 'А', 'П', 'Р', 'О', 'Л', 'Д', 'Ж', 'Э', 'Enter',
  'Shift', 'Я', 'Ч', 'С', 'М', 'И', 'Т', 'Ь', 'Б', 'Ю', ',', '↑', 'Shift',
  'Ctrl', 'Win', 'Alt', 'Space', 'Alt', '←', '↓', '→', 'Ctrl',
];
export const keyRuShiftSmall = [
  'ё', '!', '"', '№', ';', '%', ':', '?', '*', '(', ')', '_', '+', 'Backspace',
  'Tab', 'й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ', '|', 'Del',
  'Caps Lock', 'ф', 'ы', 'в', 'а', 'п', 'р', 'о', 'л', 'д', 'ж', 'э', 'Enter',
  'Shift', 'я', 'ч', 'с', 'м', 'и', 'т', 'ь', 'б', 'ю', ',', '↑', 'Shift',
  'Ctrl', 'Win', 'Alt', 'Space', 'Alt', '←', '↓', '→', 'Ctrl',
];
export const keyRu = [
  'ё', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'Backspace',
  'Tab', 'й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ', '\\', 'Del',
  'Caps Lock', 'ф', 'ы', 'в', 'а', 'п', 'р', 'о', 'л', 'д', 'ж', 'э', 'Enter',
  'Shift', 'я', 'ч', 'с', 'м', 'и', 'т', 'ь', 'б', 'ю', '.', '↑', 'Shift',
  'Ctrl', 'Win', 'Alt', 'Space', 'Alt', '←', '↓', '→', 'Ctrl',
];
export const keyEn = [
  '`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'Backspace',
  'Tab', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\', 'Del',
  'Caps Lock', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', 'Enter',
  'Shift', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', '↑', 'Shift',
  'Ctrl', 'Win', 'Alt', 'Space', 'Alt', '←', '↓', '→', 'Ctrl',
];

export default {
  dataKeyRu, dataKeyEn, keyEnShift, keyEnShiftSmall, keyRuShift, keyRuShiftSmall, keyEn,
};
